# Generated by Django 4.0.3 on 2022-03-23 15:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('music', '0002_lyricratings_rating_songrating_rating'),
    ]

    operations = [
        migrations.AlterField(
            model_name='lyricratings',
            name='rating',
            field=models.IntegerField(default=0),
        ),
    ]
