# Generated by Django 4.0.3 on 2022-03-23 17:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('music', '0003_alter_lyricratings_rating'),
    ]

    operations = [
        migrations.AlterField(
            model_name='artistrating',
            name='rating',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='songrating',
            name='rating',
            field=models.IntegerField(default=0),
        ),
    ]
